name: Publish Python ğŸ distributions ğŸ“¦ to TestPyPI and PyPI

on: 
  push:
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install-n-test:
    name: Install and Test current version
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install requirements
        run: python -m pip install --user wheel 

      - name: Install Slack_handler
        run: pip install --user -e .

      - name: Run all tests
        run: |
          pip install --user pytest
          pytest -vvv tests/

  build-n-publish:
    needs: install-n-test
    name: Build and publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        
    - name: Install pypa/build
      run: pip install --user build
     
    - name: Build a binary wheel and a source tarball
      run: build --sdist --wheel --outdir dist/
    
    - name: Publish distribution ğŸ“¦ to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    
    - name: Publish distribution ğŸ“¦ to PyPI (Release)
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN_SH }}
    
